### ISSUE TITLE
향후 계획?

### ISSUE THREAD

**Issue by wonwooddo** [MrSyee/pg-is-all-you-need#20]
AI robotics에서 강의 잘 들었습니다.
앞으로 이 github에 더 많은 RL 알고리즘 개발&공유 하실 예정이 있으신지 궁금합니다.
(A3C, D4PG, rainbow-dqn...)
감사합니다.

**Comment by MrSyee** [comment]
안녕하세요. @wonwooddo 님
강의 잘 들어주셔서 감사합니다. :)

먼저 이 Repo에서는 필요에 따라 한 두개 정도 추가할 생각은 있습니다만 알고리즘 수를 크게 늘릴 계획은 아직 없습니다 . DQN 계열은 저희가 이전에 배포한 첫번째 시리즈인 [Rainbow-is-all-you-need](https://github.com/Curt-Park/rainbow-is-all-you-need) 레포에서 확인하실 수 있습니다. Rainbow의 요소들을 이 레포와 같은 포맷으로 잘 구현해 두었으니 보시면 좋을 것 같습니다.

감사합니다.
